# Generated by Django 5.2.1 on 2025-06-01 23:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название траектории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('difficulty', models.IntegerField(choices=[(1, 'Начинающий'), (2, 'Продвинутый'), (3, 'Эксперт')], default=1, verbose_name='Уровень сложности')),
                ('duration_months', models.IntegerField(verbose_name='Длительность (месяцы)')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Предварительные требования')),
                ('learning_outcomes', models.TextField(verbose_name='Результаты обучения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Образовательная траектория',
                'verbose_name_plural': 'Образовательные траектории',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название профессии')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('required_algorithms', models.TextField(verbose_name='Необходимые алгоритмы')),
                ('required_skills', models.TextField(verbose_name='Необходимые навыки')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от (руб.)')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до (руб.)')),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=20, verbose_name='Уровень опыта')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (CSS класс)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная профессия')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название шага')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('step_type', models.CharField(choices=[('theory', 'Теория'), ('practice', 'Практика'), ('project', 'Проект'), ('course', 'Курс'), ('book', 'Книга')], max_length=20, verbose_name='Тип шага')),
                ('estimated_hours', models.IntegerField(verbose_name='Примерное время (часы)')),
                ('resources', models.TextField(verbose_name='Ресурсы и ссылки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок выполнения')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('education_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='career.educationpath', verbose_name='Образовательная траектория')),
            ],
            options={
                'verbose_name': 'Шаг траектории',
                'verbose_name_plural': 'Шаги траектории',
                'ordering': ['education_path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('external_url', models.URLField(verbose_name='Ссылка на вакансию')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='Внешний ID')),
                ('source', models.CharField(max_length=50, verbose_name='Источник (hh.ru, etc.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок интервью')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('interviewee_name', models.CharField(max_length=100, verbose_name='Имя интервьюируемого')),
                ('interviewee_position', models.CharField(max_length=200, verbose_name='Должность')),
                ('interviewee_company', models.CharField(max_length=200, verbose_name='Компания')),
                ('interviewee_photo', models.ImageField(blank=True, null=True, upload_to='interviews/', verbose_name='Фото интервьюируемого')),
                ('interview_type', models.CharField(choices=[('text', 'Текстовое'), ('video', 'Видео'), ('audio', 'Аудио'), ('mixed', 'Смешанное')], default='text', max_length=20, verbose_name='Тип интервью')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание интервью')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='interviews/audio/', verbose_name='Аудиофайл')),
                ('key_insights', models.TextField(verbose_name='Ключевые выводы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Интервью',
                'verbose_name_plural': 'Интервью',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='educationpath',
            name='target_profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.profession', verbose_name='Целевая профессия'),
        ),
    ]
