# Generated by Django 5.2.1 on 2025-06-01 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название челленджа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('challenge_type', models.CharField(choices=[('speed', 'На скорость'), ('efficiency', 'На эффективность'), ('memory', 'На память'), ('quiz', 'Викторина'), ('game', 'Мини-игра')], max_length=20, verbose_name='Тип челленджа')),
                ('difficulty', models.IntegerField(choices=[(1, 'Новичок'), (2, 'Любитель'), (3, 'Профессионал'), (4, 'Эксперт')], default=1, verbose_name='Уровень сложности')),
                ('algorithm_required', models.CharField(blank=True, max_length=100, verbose_name='Требуемый алгоритм')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='Лимит времени (секунды)')),
                ('max_score', models.IntegerField(default=100, verbose_name='Максимальный балл')),
                ('instructions', models.TextField(verbose_name='Инструкции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Челлендж',
                'verbose_name_plural': 'Челленджи',
                'ordering': ['difficulty', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Счет')),
                ('time_spent', models.FloatField(verbose_name='Время (сек)')),
                ('moves_count', models.IntegerField(default=0, verbose_name='Количество ходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата игры')),
            ],
            options={
                'verbose_name': 'Результат игры',
                'verbose_name_plural': 'Результаты игр',
                'ordering': ['-score', 'time_spent'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Дневной'), ('weekly', 'Недельный'), ('monthly', 'Месячный'), ('all_time', 'Всех времен')], max_length=20, verbose_name='Период')),
                ('total_score', models.IntegerField(default=0, verbose_name='Общий счет')),
                ('challenges_completed', models.IntegerField(default=0, verbose_name='Челленджей завершено')),
                ('average_time', models.FloatField(blank=True, null=True, verbose_name='Среднее время')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Запись лидерборда',
                'verbose_name_plural': 'Лидерборд',
                'ordering': ['period', 'position'],
            },
        ),
        migrations.CreateModel(
            name='MiniGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название игры')),
                ('game_type', models.CharField(choices=[('drag_sort', 'Перетаскивание'), ('click_sort', 'Клик-сортировка'), ('memory_sort', 'Сортировка по памяти'), ('speed_sort', 'Скоростная сортировка')], max_length=20, verbose_name='Тип игры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('difficulty', models.IntegerField(choices=[(1, 'Новичок'), (2, 'Любитель'), (3, 'Профессионал'), (4, 'Эксперт')], default=1, verbose_name='Сложность')),
                ('config', models.JSONField(default=dict, verbose_name='Конфигурация игры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Мини-игра',
                'verbose_name_plural': 'Мини-игры',
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Набранные баллы')),
                ('time_spent', models.FloatField(verbose_name='Время выполнения (сек)')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('attempts_count', models.IntegerField(default=1, verbose_name='Номер попытки')),
                ('answer_data', models.JSONField(blank=True, null=True, verbose_name='Данные ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата попытки')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge', verbose_name='Челлендж')),
            ],
            options={
                'verbose_name': 'Попытка челленджа',
                'verbose_name_plural': 'Попытки челленджей',
                'ordering': ['-created_at'],
            },
        ),
    ]
